include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dangling_library_doc_comments: ignore

linter:
  rules:
    file_names: false
    non_constant_identifier_names: false
    avoid_print: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
